### PR TITLE
Fix statusmessage and form validation selectors for Barceloneta LTS

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by fredvd** [comment]
Are these fixes compatible with Plone 5.2 ? Otherwise maybe a 3.X branch for mockup should be created for Plone 5.2 support and mockup master can be used for Plone 6.

**Comment by petschki** [comment]
Changes are all backwards compatible. This is a bugfix for https://github.com/plone/mockup/pull/975

**Pull request merged**
