### PR TITLE
Fix recurrencewidget to initialize saved value correctly and fix RDATE and EXDATE editing

### LINKED ISSUE #1266: `pat-recurrence`: selected dates don't change when "Repeats" field changes
When you add a recurrence to an event, and then change the repetition, the selected dates don't change.
You need to click in / change another field to make the selected dates list change.

Tested on Plone 6.0.0 final.

See this video, taken on demo :

recurrence

cc @petschki

### PR DESCRIPTION
**Pull request by petschki**
fixes #1266 

This is also partly a code cleanup of the old jquery-recurrencewidget approach. The main fix is to save the parsed `RRULE` object to the `textarea['ical']` attribute instead of the jquery form ... this gives us a sane state during editing the recurrence widget multiple times.

### CODE REVIEW

**Review by thet — APPROVED** [review]
:+1:

**Review by laulaz — APPROVED** [review]
Thanks @petschki 👍

**Comment by petschki** [comment]
@laulaz  I just realized, that this not really fixes your issue when changeing the select ... give me a few more minutes ...

**Comment by petschki** [comment]
now fixed ... I'll merge and release. @thet can we release this in staticresources then too? I need this for my projects too ...

**Comment by petschki** [comment]
oh my ... just found out that when creating an event the ajax call to `@@json_recurrence` breaks ... I'll do a new PR with the fix. We really should use a JS library to generate the events from the RRULE instead of calling the backend ... see https://github.com/plone/mockup/issues/1210

**Pull request merged**
