### PR TITLE
jsi18n -> plonejsi18n

### PR DESCRIPTION
**Pull request by kiorky**
This refs plone/plone.app.widgets@4b397c3

### CODE REVIEW

**Comment by kiorky** [comment]
cc @ebrehault @datakurre  @vangheem

**Comment by datakurre** [comment]
+1

This shouldn't hurt anyone, because AFAIK in Plone 5 p.a.widgets should be merged into CMFPlone anyway.

**Comment by vangheem** [comment]
This is fine. I'm not sure I understand why the change is necessary though.

**Comment by vangheem** [comment]
and that test failure doesn't make any sense.

**Comment by datakurre** [comment]
@vangheem For Plone 4.3, which does not jsi18n info in its p.a.layout version.

**Comment by vangheem** [comment]
I see. That is fine. FWIW, I'm not worrying about 4.3 for now on with mockup and plone.app.widgets. It's been holding us back and too much work to try and make everything work both ways. If someone else wants to try, that's fine.

**Pull request merged**
