### PR TITLE
`pat tinymce` Improve tinymce async initialization

### PR DESCRIPTION
**Pull request by frapell**
This PR fixes gh-1253 and also I have refactored the `initLanguage` method to not use a callback, but instead properly await it.
In addition, I added a check so only valid plugins (plugins that can be imported) are included.

### CODE REVIEW

**Comment by frapell** [comment]
@petschki @thet If you guys could review this, I think it is important we can include these fixes before Plone 6.0 final is released...

**Review by petschki — APPROVED** [review]
works perfect ... nit picking: I'd change the `console.log` to `logger.debug` but otherwise approved 👍🏼

**Comment by petschki** [comment]
can we pin tinymce `^5.10.7` here too? see #1256

**Comment by frapell** [comment]
@petschki Yeah, I saw that pull request but wasn't sure how it is handled, should I add that pin in this PR? or should we merge that one?

**Comment by petschki** [comment]
if you add the pin here, dependabot closes his PR automatically ...

**Comment by frapell** [comment]
@petschki bumped the versions and replaced `console.log` with `log.debug` I squashed all commits in one and force pushed, since I messed up by using " ` " in the commit message

**Pull request merged**
