### PR TITLE
pat-recurrence classic-ui

### PR DESCRIPTION
**Pull request by petschki**
Someone hat do to it ... 

- [x] move code from `jquery.recurrenceinput.js` to `pat-recurrence`
- [x] remove `jQuery.tools.dateinput` -> native `<input type=date />` is used now
- [x] remove `jQuery.tools.overlay` -> `pat-plone-modal` is used now
- [x] update templates to `_.template`
- [x] update forms to BS5
- [x] set form values according to saved RRULE data (there's something missing ... have to check)
- [x] use common date formatting utility and apply to all dates

left old | right new

recurrence-widget

### CODE REVIEW

**Comment by pbauer** [comment]
What am I doing wrong? The modal looks like this for me: 
recurrence

I did `yarn install` and `npm run start:webpack` in mockup.

**Comment by pbauer** [comment]
Your screenshot makes a lot of sense though.

**Comment by thet** [comment]
Great achievement and big surprise :) !
But I get this JS error and the same visual problems like @pbauer

**Comment by petschki** [comment]
Yes still some work to do.  @pbauer looks like the visible field initialization doesn't work.  @thet your screenshot didn't upload.

**Comment by thet** [comment]
@petschki updated

**Comment by petschki** [comment]
sorry, fixed initialization of empty recurrence field ... should work now.

**Comment by petschki** [comment]
any chance to get this merged? I think it works much better than before ...

**Review by mauritsvanrees — APPROVED** [review]
The errors are gone. LGTM. Thanks!

**Pull request merged**
