### PR TITLE
Add sticky-kit pattern

### PR DESCRIPTION
**Pull request by bogdangi**
There is simple integration of [sticky kit](leafo.net/sticky-kit) jQuery plugin regarding question #423 @gforcada @vangheem

### CODE REVIEW

**Comment by bogdangi** [comment]
@vangheem - it is rebased and green, I suggest we can merge, don't we?

**Comment by vangheem** [comment]
I was about to but second guessed myself when considering if this belongs in mockup core.

I wonder if we need to revitalize the mockup extras package.

Thoughts?

**Comment by bogdangi** [comment]
+1

**Comment by bogdangi** [comment]
@vangheem I can revitalize the mockup extras, but that package in not touched for a years.
Does it means that mockup extras is not useful anymore?

**Comment by jcbrand** [comment]
@bogdani, @vangheem, @benniboy We can work on this at the Alpine sprint (starting today). Just need some context please.

**Comment by bogdangi** [comment]
Dear @jcbrand there is package https://github.com/plone/mockup-extra that has to be revitalized and we can put this feature for the sticky content there.

But first of all we have to decide do we need revitalized mockup-extra.

**Comment by jcbrand** [comment]
@bogdangi Looked to me like it was already agreed upon. :)

**Comment by bogdangi** [comment]
Ok, then lets move it to mockup-extra.

**Comment by jensens** [comment]
So I close this PR here, but keep the branch. Please move it, but do not forget to remove it after move is done.

**Comment by jcbrand** [comment]
Thanks @jensens 

@bogdangi Unfortunately we didn't get around to moving this during this sprint.

I'll take a look at it after pull request #460 has been merged. This pattern will then require some small changes as mentioned in the pull request.

**Pull request closed without merging**
