### PR TITLE
Upgrade sinon

### PR DESCRIPTION
**Pull request by davilima6**
WIP. Currently failing with:

```
  Structure traverse links
    ✗ test navigate to folder push states
	undefined is not an object (evaluating 'history.pushed.url')
	tests/pattern-structure-test.js:1306:28

    ✗ test navigate to folder push states - urlStructure
	undefined is not an object (evaluating 'history.pushed.url') A
	tests/pattern-structure-test.js:2153:28

    ✗ test navigate to folder push states - pushStateUrl
	undefined is not an object (evaluating 'history.pushed.url')
	tests/pattern-structure-test.js:2190:28
```

See: https://github.com/plone/mockup/pull/913#issuecomment-505065684

### CODE REVIEW

**Comment by davilima6** [comment]
I also tried replacing the custom Sandbox by the default one available since Sinon 5.0 but same errors persisted.

**Comment by thet** [comment]
Green! merging.

**Comment by davilima6** [comment]
How did you make it pass? :D It was not a flaky failure, was it?

**Comment by thet** [comment]
I did some test fixes but appended to your last commit. So not easy to demonstrate :)

I renamed the ``history`` method to ``history_stub`` to not accidentally cross the global window.history.
Also, instead of ``sinon.sandbox.stub`` I used ``sinon.stub`` directly and passed the ``history_stub`` object as value instead as callFake.

Something like that.

**Comment by davilima6** [comment]
Got it, nice! I hadn't noticed the changes, thought you pushed force only to update from master. Thanks!

**Pull request merged**
