### PR TITLE
fix some i18n issues

### LINKED ISSUE #991: Improve i18nzation of mockup
See https://github.com/plone/Products.CMFPlone/issues/2188#issuecomment-646535054

### PR DESCRIPTION
**Pull request by erral**
Fixes #991

The changes are:

- Open tooltip is translated
- Edit tooltip is translated
- All values of action dropdown are translated (Copy, Move to top, move to bottom, set as default page, select contained items).
- "No sorting" in filter menu is translated

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
Thank you @erral for stepping in!
Did you follow the instructions I added in the https://github.com/plone/mockup README? Was they useful?
Did you test regenerating the widget.pot, resync the po and really translate?
You can already commits the changes in plone.app.locales if you want, even if this PR is not merged yet.

For the changes to be in a future Plone release, a PR for plone.staticresources will also need to be done. It's a little bit of work and we already merged one for Plone 5.2.2 so it's probably too late for this version. Otherwise It will be Plone 5.2.3 for sure. :-)

I leave the PR open for now if you're brave enough to fix other issues (title on some dialog maybe?) of if other want to continue fixing issues in this branch.

**Comment by erral** [comment]
Yes, I made everything following your instructions, change files, debug mode, recreated the pot file, transalted, deleted the localStorage, ... and the changes are present. A bit hard but useful.

I will investigate more changes and will create specific issues for each one to track them down. That would be better.

**Comment by vincentfretin** [comment]
Cool. FYI you don't really need to create an issue in this repo to have a number for the changelog entry, you can use the PR number. What I do generally is create a branch, push it, create the PR and then add the changelog entry, amend my commit and push force (when I want only one commit in my PR), otherwise you can add a commit "add changelog entry", it works too!

```
git add news/xxx.bugfix
git commit --amend
git push --force
```

**Comment by erral** [comment]
I will merge this PR and regenerate the widgets.pot file in plone.app.locales. These were small changes, the other issues have their own size to be treated independently I think.

**Comment by vincentfretin** [comment]
Ok then, before we merge, can you please be more precise in the changelog entry?

**Comment by vincentfretin** [comment]
btw you know i18nzation doesn't make sense? :-)
i18n is first letter i + 18 letters between the first and last letter of the word internationalization + last letter n
so i18nzation would mean internationalizationzation

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
You can merge when jenkins is green.

**Comment by vincentfretin** [comment]
Can you please commit the translations in plone.app.locales?

**Comment by erral** [comment]
done.

**Pull request merged**
