### PR TITLE
Contextual menu

### PR DESCRIPTION
**Pull request by b4oshany**
Added the following contextual menu to file tree for the theme mapper:

* New File
* New Folder
* Rename
* Delete

resized-contextualmenu

### CODE REVIEW

**Comment by jensens** [comment]
A context menu would be also a great standalone pattern! Would it be too much to make it one?

**Comment by datakurre** [comment]
@jensens Unfortunately, this requires jqtree, which is only used by filemanager, so standalone would not be possible with the current libraries (and then again standalone might not easily work with jqtree).

**Comment by datakurre** [comment]
This pull requires jqtree-contextmenu being added into Products.CMFPlone. @b4oshany no hurry, just refer to this issue when you have pull at CMFPlone, and ask help if you have issues in adding all the required stuff

* [ ] jqtree.contextmenu in CMFPlone
* [ ] resource registrations in CMFPlone (to work on new sites)
* [ ] registry upgrade lines in plone.app.upgrade (to upgrade existing sites)

**Comment by b4oshany** [comment]
I made the changes to [CMFPlone](https://github.com/plone/Products.CMFPlone/pull/2090) and [plone.app.upgrade](https://github.com/plone/plone.app.upgrade/pull/126) over a week ago. I just realised the build has finally finished on Jenkins. However, I noticed that there"s a failure for [plone.app.upgrade in jenkins](http://jenkins.plone.org/job/pull-request-5.0/116/console) as seen in the screenshot below:

image

This error seems unrelated to the changes I've made.

**Comment by datakurre** [comment]
* [ ] https://github.com/plone/plone.app.upgrade/pull/126
* [ ] https://github.com/plone/Products.CMFPlone/pull/2090

**Comment by datakurre** [comment]
Or package.json. It seems to be available also from npmjs https://www.npmjs.com/package/cs-jqtree-contextmenu

**Comment by datakurre** [comment]
I only now noticed that this could only pass on Plone 5.1, because Plone 5.0 requires mockup 2.1.x

**Comment by datakurre** [comment]
@b4oshany :+1:

The remaining issue is that this master branch is for CMPlone master (5.1.x), while your current pulls for CMFPlone and plone.app.upgrade are for Plone 5.0.x. AFAIK we can only merge this pull when there are versions for Plone 5.1 (and those Plone 5.0 can be merged only when there's backport of thi spull for Mockup 2.1.x branch)

**Comment by datakurre** [comment]
Should be merged with

* [ ] https://github.com/plone/plone.app.upgrade/pull/131

**Pull request merged**
