### PR TITLE
Fix for loading country specific languages codes

### PR DESCRIPTION
**Pull request by lyralemos**
With this fix, country specific language codes are correctly loaded. Fixes plone/Products.CMFPlone#949

As language codes are obtained via lang property in the html tag, there is an inconsistency with Plone locales code base. For instance, Brazilian Portuguese lang attribute is pt-br, but in plone locales is referred to as pt_BR.

This code does a simple transformation on the language code so that correct translations are loaded.

### CODE REVIEW

**Comment by davilima6** [comment]
@lyralemos will sign and send over the Contributor Agreement today. Thanks! (also kudos to @claytonc who initially helped with the solution=)

**Comment by lyralemos** [comment]
I've already signed the agreement.
Code was committed using a different e-mail which I just added to my GitHub account.

**Comment by davilima6** [comment]
I'd squash all commits before merge.

**Comment by thet** [comment]
LGTM

**Comment by lyralemos** [comment]
I've managed to run the tests locally and realized were the problem is.
For some reason tests are falling if I don't check if currentLanguage is different that en-us.

Should I create a new PR? Or can I still commit changes here?

**Comment by gforcada** [comment]
@lyralemos a new pull request would be best, thanks for having a quick look at it!!

**Pull request merged**
