### PR TITLE
Include Tinymce 4.6.1

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Comment by thet** [comment]
@frapell there are test failures - can you please them?
IIRC for tinymce inline to work, some TinyMCE API calls are made. Maybe something has changed here? (as it fails for form saving)

**Comment by frapell** [comment]
I Tried to find why this is happening, but couldn't... I created a ticket for tinymce in https://github.com/tinymce/tinymce/issues/3674

In the meantime, I created a pull request for getting tinymce 4.5.6 https://github.com/plone/mockup/pull/766 until I can figure out what's going on with 4.6.1, I will do the needful for CMFPlone

**Comment by frapell** [comment]
Not quite sure what's going on... the guy from https://github.com/tinymce/tinymce/issues/3674 showed me in http://fiddle.tinymce.com/CQfaab that by doing:

```
tinymce.activeEditor.setContent('foobar');
tinymce.activeEditor.save();
console.log($('textarea').val());
```

it does work fine, and the content is set on the textarea, however, from the test, I do:

```
tinymce.tiny.setContent('<p>foobar</p>');
tinymce.tiny.save();
$el.val()
```

And I get empty string...

**Comment by thet** [comment]
We already have 4.7.6 since https://github.com/plone/mockup/pull/832
Closing this.

**Pull request closed without merging**
