### PR TITLE
maint: define YARN in our Makefile.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes issue #1254.

### CODE REVIEW

**Comment by petschki** [comment]
Is this really needed? `YARN ?= npx yarn` is already defined in the base Makefile here: https://github.com/Patternslib/dev/blob/main/Makefile#L15

**Comment by petschki** [comment]
ah ... sorry, saw the issue too late ... never had this. maybe because of `nvm` installed here...

**Comment by mauritsvanrees** [comment]
I think you will have the same issue in a fresh clone, or when you remove node_modules. I can't imagine how it works without this.
I use nvm as well.

**Comment by petschki** [comment]
confirmed. fresh clone raises error. this PR fixes it. I'll merge.

**Pull request merged**
