### PR TITLE
typo fix in error message

### PR DESCRIPTION
**Pull request by tkimnguyen**

### CODE REVIEW

**Comment by tkimnguyen** [comment]
Do I need to make a similar change in plone.app.locales/widgets.pot to the matching msgid?

**Comment by thet** [comment]
@tkimnguyen yes that would be needed.
That's the downside of using the actual message strings as message id's :(

**Comment by tkimnguyen** [comment]
ok I made this PR to match: https://github.com/collective/plone.app.locales/pull/177

**Comment by tkimnguyen** [comment]
(It's kind of weird for a core package to depend on a collective one...)

**Comment by thet** [comment]
tnx!

**Pull request merged**
