### PR TITLE
TinyMCE 6

### PR DESCRIPTION
**Pull request by petschki**
~~Note: There are renamed menu and toolbar items for the format menu. You have to rename them manually right now.~~

We map the old names now here until the configuration values changed.

### CODE REVIEW

**Comment by thet** [comment]
@petschki can we add aliases for these old values (`formats` and `styleselect`) in Mockup itself? that might be easier than adding an upgrade step and it would be better backwards compatible - you could use Mockup with older versions of Plone too, maybe.

**Review by thet — CHANGES_REQUESTED** [review]
I think we need aliases for the old tinymce toolbar/menu values. Plus, after merging we also need to update the default options for the tinymce control panel to reflect those new values.

Other than that: :tada: :100:

**Review by thet — APPROVED** [review]

**Comment by petschki** [comment]
just fixed the tests.

I think semantic versioning would require a `5.2.0` release of this ... should we got with an alpha first? and `plone.staticresources = 2.2.0` too ...

**Review by thet — APPROVED** [review]

**Comment by thet** [comment]
Yes for 5.2.0.
An alpha version might be good to check if the integration works properly with Plone.

**Comment by MrTango** [comment]
great job! thx

**Pull request merged**
