### PR TITLE
Fix misalignment in regular Select 2 widgets

### PR DESCRIPTION
**Pull request by davilima6**
Fixes plone/Products.CMFPlone#2785

### CODE REVIEW

**Comment by davilima6** [comment]
@jenkins-plone-org please run jobs

**Comment by davilima6** [comment]
@jenkins-plone-org please run jobs

**Comment by davilima6** [comment]
@jenkins-plone-org please run jobs

**Comment by davilima6** [comment]
@MrTango, @pbauer: could you please check if this fixes the issue while still keeping Related Items widget working as before?

You can test by putting plone-logged-in bundle in Debug CSS mode. For testing in production mode, you need to use `fix-tag-widget-misalignment` branch from plone/plone.staticresources.

We should merge plone/plone.staticresources#21 after we merge this one.

**Comment by MrTango** [comment]
@davilima6 looks good to me, thx a lot

**Comment by davilima6** [comment]
Welcome!

**Pull request merged**
