### PR TITLE
WIP: discussion pattern.

### PR DESCRIPTION
**Pull request by tmog**
Basic test mocks and reply form cloning functionality in place.
Actions parameter for specifying additional button behaviours half implemented.

### CODE REVIEW

**Comment by jensens** [comment]
@tmog @jcbrand any opinion how to proceed with this mockup pattern?

**Comment by jcbrand** [comment]
@jensens I can take a look at this next week (in bed with the flu this week).

**Comment by jensens** [comment]
any update here?

**Comment by jcbrand** [comment]
I checked out this branch and then merged master into it.

This branch is quite outdated (~500 commits behind master) and some of the files here have been moved around in master.

Nevertheless I fixed the conflicts and put the files in their proper place. I also fixed tab problem and some jshint issues.

My work is in a new branch: https://github.com/plone/mockup/tree/tmod-discussion-merged

However, the tests now fail with an **expect** assert. It doesn't look like the tests actually ever passed and I think the tabbing issue only masked the underlying test failures.

Besides that, there are code smells. Outcommented code, global variables, syntax errors etc.

I'm not aware of how much of a priority this pattern is, but looks like it needs quite a bit more work before it could be merged.

This pull request should be rejected. Any new pull request will in any case have to come from the new branch I created. But even then, there are failing asserts in the tests and there's no proof that the pattern actually at all works.

CC @jensens @vangheem @tmog

**Comment by vangheem** [comment]
I agree to reject this.

**Comment by jensens** [comment]
@tmog at this state we cant merge. @tmog will you fix this including tests? if not I propose to close this PR, otherwise keep it open and wait for updates.

**Comment by jensens** [comment]
since there is no response i close this now. if you plan to work on this please just reopen this issue.

**Comment by jensens** [comment]
@kiorky whats the plan with this one?

**Comment by jensens** [comment]
i close this now. if you really plan to work on this please just reopen this issue.

**Pull request closed without merging**
