### PR TITLE
Fix and upgrade the testing stack

### PR DESCRIPTION
**Pull request by sunew**
- Fix WARN [watcher]: Pattern "..../patterns/foo.js" does not match any file, 
  by excluding all requirements ending with '-url', 
  since they point to a folder and not to a .js file. 
  The folder contents are already included by 'patterns/**/*'.

- Move installation and config of sinon from bower+requirejs to karma-sinon.

- Remove chai - it is unused. The assertions being used are from 'expect', installed via bower.json

- Upgrade some build and testing tools: grunt, karma, mocha, their plugins, coveralls, and browser launchers.

### CODE REVIEW

**Comment by sunew** [comment]
See https://github.com/plone/mockup/issues/865

**Comment by sunew** [comment]
TODO: fix coveralls - has not been run in ages. Perhaps its fixed with this PR...

**Comment by frapell** [comment]
@sunew I am liking this a lot :) let me know when you are done, so I can respond to your review request

**Comment by sunew** [comment]
@frapell cool! thanks:) I will work on it a little more.

**Comment by sunew** [comment]
Coveralls integration is now working.

**Comment by sunew** [comment]
@frapell I am done for now - please review :)
There are still things to do, but lets get this integrated. I am starting the jenkins tests.

**Comment by sunew** [comment]
One more todo for now:
The mockup version of less is behind the cmfplone version.
Trying to bring them in sync.

**Comment by sunew** [comment]
@frapell ready for review
See also https://github.com/plone/Products.CMFPlone/pull/2517

**Pull request merged**
