### PR TITLE
Make it possible to customize the available image classes

### PR DESCRIPTION
**Pull request by davisagli**
This adds an option to the tinymce pattern to make it possible to configure the available image classes / alignment options. I want to use this on one site to provide a "full width image" option.

### CODE REVIEW

**Comment by frapell** [comment]
LGTM :)

**Comment by davisagli** [comment]
Thanks for merging. Now I need to make a PR for CMFPlone to update the plone-loggedin, right? Or is that part of the release process?

**Comment by frapell** [comment]
@davisagli Yeah, doc is a bit hard to find, but AFAIK, you can follow https://github.com/plone/Products.CMFPlone/blob/master/DEVELOPING_BUNDLES.rst

**Comment by thet** [comment]
@davisagli creating a bundle is not yet part of the release process. as soon as this is finished (it's almost-done) - https://github.com/plone/Products.CMFPlone/issues/1653 - it will get a bit easier.

the process is:
- create a bundle with ``plone-create-bundle``,
- update the last_compilation timestamp for the bundle which was changed in CMFPlone/profiles/dependencies/registry.xml
- make the obligatory changelog entry (one "Update mockup" per release is enough)
- And - if not done yet - create a upgrade step which re-imports the last_compiled timestamp.

All of that isn't really documented.

**Pull request merged**
