### PR TITLE
feat: add option to select moment format in structure

### PR DESCRIPTION
**Pull request by Gagaro**
I would like to be able to choose the moment formatting in structures. As I am fairly new to mockup, I don't know if this is the best way to do it (I tried with html attributes but it seems to not working because of the Moment pattern being initialized in JS ?).

Please also note that this is not based on master because of #589.

### CODE REVIEW

**Comment by jensens** [comment]
- changelog entry is missing
- your change the default from ``relative`` to ``calendar`` (no idea what implication it has), but it feels wrong.

**Comment by Gagaro** [comment]
Good catch, I tested it and forgot to put back the relative value...

Changelog entry added.

Thanks for the review.

**Comment by vangheem** [comment]
Did you re-test your change? I wonder if you changing the default is the only thing that made this work. I'm not sure ``self.options.app.momentFormat`` would get you the right option.

**Comment by Gagaro** [comment]
I just retested it and it works fine. I find the app variable using a debugger as I wasn't sure how to get an option from a parent pattern. Please let me know if you know of a better solution.

**Comment by vangheem** [comment]
Okay, good. I also didn't remember how those options were copied over :)

Could you rebase?

**Comment by Gagaro** [comment]
Done

**Pull request merged**
