### PR TITLE
PickADate buttons clear and now 2.1.x

### PR DESCRIPTION
**Pull request by thet**
Backport to 2.1.x branch from: https://github.com/plone/mockup/pull/730

/cc @tomgross

### CODE REVIEW

**Comment by thet** [comment]
Jenkins: http://jenkins.plone.org/job/pull-request-5.0/1725/

**Comment by thet** [comment]
http://jenkins.plone.org/job/pull-request-5.0/1780/

**Comment by thet** [comment]
Jenkins: http://jenkins.plone.org/job/pull-request-5.0/1788/

**Comment by thet** [comment]
Safe alignment for 2.1.x with master branch. Merging now.

**Comment by tomgross** [comment]
@thet It seems to work as expected. Thanks!

You removed the _Clear_-button in the time dropdown. The picker_footer  is still visible in the date dropdown with the _Close_ and _Today_ buttons present there as well. Can we remove it?

**Comment by tomgross** [comment]
Is this too much? https://github.com/plone/mockup/pull/739

**Pull request merged**
