### PR TITLE
add content icon to relateditems pattern

### PR DESCRIPTION
**Pull request by petschki**
see #442

### CODE REVIEW

**Comment by vangheem** [comment]
How does this work OOTB? Does plone give a meaningful value for getIcon all the time. Should those img tags be conditionally in the template?

**Comment by davisagli** [comment]
It only returns a value for types that have an icon_expr set in portal_types. Most of the core types don't have an icon there (they get icons via CSS) but some addons still do. In plone.app.contenttypes file and image have a special getIcon indexer which gets an icon from the mimetypes_registry based on the file mimetype

**Comment by petschki** [comment]
So this is what the latest change brings OOTB:
bildschirmfoto 2015-02-23 um 10 30 13

**Comment by vangheem** [comment]
I'm okay with this. This way you can have customized icons thumbnails and icons are the fallback.

Side note: We should match the icons used in Plone 5(defined as only css rules) back into the filesystem icon image files defined.

**Pull request merged**
