### PR TITLE
fixed external description translation

### PR DESCRIPTION
**Pull request by parruc**
Fixed wrong translation text option in links popup

### CODE REVIEW

**Comment by vincentfretin** [comment]
You can merge.

**Comment by vincentfretin** [comment]
I squashed and merged in master and 2.7.x

**Comment by vincentfretin** [comment]
Of course someone will need to rebuild the bundles if we want the fix in Plone 5.1.7 or Plone 5.2.3.

**Comment by parruc** [comment]
> I squashed and merged in master and 2.7

Thank you

**Comment by mauritsvanrees** [comment]
A rebuild of bundles for Plone 5.1 would be handy about now.
I might have a look myself, but I haven't done this before.

**Pull request merged**
