### PR TITLE
Relateditems refactoring + more

### PR DESCRIPTION
**Pull request by thet**
# Related Items refactorings
- Make "search" and "browse" mode user-selectable via buttons.
- Remove obsolete tree widget, use "browse" mode instead.
- Let "search" mode search recursively.
- Let "browse" mode start from current path.
- Immediately open select2 results when clicking on "Browse" or "Search".
- Show only selectable items in "search" mode, if defined.
- Show only selectable and folderish items in "browse" mode, if selctable items are defined.
- Exclude already selected items in result list.
- Default closeOnSelect to true.
- Show "Open folder" arrow only when in "browse" mode.
- Seperate templates from JavaScript into xml files.
- Allow optional image and file upload (especially useful for image and file reference widgets).
- Allow configuration of "favorites" to quickly switch the current path via a dropdown menu.

# Structure pattern refactorings
- Prevent popovers to be closed when clicking on non-visible elements which still use screen space (those with visibility: hidden or opacity: 0). That in addition to elements, which are not visible at all and do not use screen space (display: none). Prevents upload form in structure pattern to be closed when opening the file selection tool.
- Use thumb scale for image preview in rename dialog and optimize the rename dialog layout.
- Remove pat-relateditems path selection widget but make sure, the path can still be set via navigation within the structure pattern.
- Add action menu item option ``css`` and always do a pattern scan on action menu items. This allows to set patterns on them, e.g. to open a modal or use tooltips.
- Sort Available Columns dialog entries.

# TinyMCE
    - Simplify definition of custom imageScales by passing a JSON string.

# Contentloader
- Contentloader pattern: Remotely loaded HTML content is wrapped in a ``div`` element, to allow jQuery to find also the first element. jQuery starts to search at it's first child element.

# Upload pattern
- Add option ``allowPathSelection`` to disable the related items path selection.

# Related PRs
https://github.com/plone/Products.CMFPlone/pull/1709
https://github.com/plone/plone.app.content/pull/102
https://github.com/plone/plone.app.multilingual/pull/245
https://github.com/plone/plone.app.upgrade/pull/83

Rebased from https://github.com/plone/mockup/pull/676 + extended

### CODE REVIEW

**Comment by thet** [comment]
Sorry for this being such a big PR - I had to finish features without caring about Plone core robot tests...

**Comment by vangheem** [comment]
Can we squash these commits?

**Comment by thet** [comment]
@vangheem  I'll do - all cleanup commits into one, each pattern into one commit.

**Comment by fgrcon** [comment]
https://github.com/plone/mockup/pull/696/commits/4ebd1f6fc10c47e0a6cd8f35791c0fb32ad5d100 

This works for folder contents, rename dialog would be in https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/templates/rename.pt

icon: to small (32x32) , thumb to big? ( 128x128 ) what about tile(64x64) ?

**Comment by thet** [comment]
@fgrcon I have changed the size in the rename dialog also to ``thumb``: https://github.com/plone/plone.app.content/pull/102/files

I found the bigger icon better. In a current project we even use 175x175 pixels instead of 128x128.

But tile would also be good.

I don't have a strong preference here.

**Comment by fgrcon** [comment]
ok for me   ...

**Comment by thet** [comment]
jenkins went green on this! plz review and merge if appropriate.

/cc @seanupton @jensens @vangheem 

@seanupton I had to revert and manually re-apply your related item changes. rebasing on master was too cumbersome, because the templates have changed completly by moving them into dedicated template files.

**Comment by jensens** [comment]
So i know this code in action and it is a big step forward. +100 for merge 
I will do if I'm on my computer (no merge from phone).

**Pull request merged**
