### PR TITLE
tinymce: Do not include content.min.css as part of the bundle

### PR DESCRIPTION
**Pull request by frapell**
This PR fixes gh-838

### CODE REVIEW

**Comment by petschki** [comment]
@frapell maybe this can be merged with the test-fixes from PR #853

**Comment by petschki** [comment]
@frapell travis is green. pull-request-5.2 breaks due to a plone.restapi issue which don't belong to us https://github.com/plone/plone.restapi/issues/552 ... can we merge?

**Comment by jensens** [comment]
Yeah, merge!

**Comment by petschki** [comment]
@frapell who recompiles the resources to the 5.x branches? regarding fixing https://github.com/plone/Products.CMFPlone/issues/2430

**Comment by frapell** [comment]
@petschki I was going to do it sometime over the weekend... but if you have the time and want to do it, go ahead :)

**Comment by petschki** [comment]
@frapell uh ... if you give me some advice how to do this I'll do my best. I know how to build the bundles, but where to copy theese resources over? is there some developer documentation on this? thx.

**Comment by frapell** [comment]
@petschki Yeah, documentation for this is a bit hidden... You can find it here https://github.com/plone/Products.CMFPlone/blob/master/DEVELOPING_BUNDLES.rst 

I was not able to do it myself over the weekend, however if you wait for me to wrap https://github.com/plone/mockup/pull/850 (I hope to be able to put some time into it this week), I can include both changes... Or if you want to give it a try, go ahead :)

**Comment by petschki** [comment]
thanks for the docs ... for now I'm fine with waiting 😉

**Pull request merged**
