### PR TITLE
Fix duplicated image node when updateing already inserted image. [5.1.x]

### PR DESCRIPTION
**Pull request by petschki**
fixes https://github.com/plone/Products.CMFPlone/issues/3910

### CODE REVIEW

**Comment by pbauer** [comment]
How do I test that? I forgot how to get Plone to use the raw js instead of the minified bundle.

**Comment by petschki** [comment]
1. checkout `mockup`
2. run `yarn install && yarn start:webpack` inside the package
3. in the resource controlpanel go to the plone bundle and use `http://localhost:8000/bundle.min.js` as javascript resource

**Comment by pbauer** [comment]
I tested https://github.com/plone/plone.staticresources/pull/323 with 6.1 and it worked. 
`yarn start:webpack` didi not work:

```
mockup git:(5.1.x) $ yarn start:webpack
command not found: webpack`
```

**Review by pbauer — APPROVED** [review]

**Comment by petschki** [comment]
> 
> `yarn start:webpack` did not work:
> 

hm ... strange. maybe this is because of yarn version ... mockup only runs in `yarn < 2` 

I'll prepare releases now for the fix.

**Pull request merged**
