### PR TITLE
Fix `pat-registry` record editing modals

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
Yes, now I can properly edit the `plone.toolbar_position` again. Thanks!

**Comment by mauritsvanrees** [comment]
When I open a modal (toolbar position again) and click Cancel, nothing happens.
When I click Cancel a second time, then it works and the modal closes.

**Comment by mauritsvanrees** [comment]
Ah, no, sorry. I had switched back to the master branch to compare something. Canceling works fine the first time when using this branch.

**Comment by spereverde** [comment]
haven't tested much with mockup, couldn't find it in my omelette, so quickly tried adding it to a buildout as explained here:
http://plone.github.io/mockup/dev/#learn/mockup-autotoc_4
but that failed because of no setup.py file, see traceback
```
Develop: '/home/x0045445/projects/testmockup/devel/mockup'
Traceback (most recent call last):
  File "/tmp/tmpax5bjcc0", line 13, in <module>
    with open('/home/x0045445/projects/testmockup/devel/mockup/setup.py') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/x0045445/projects/testmockup/devel/mockup/setup.py'
While:
  Installing.
  Processing develop directory '/home/x0045445/projects/testmockup/devel/mockup'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/x0045445/projects/testmockup/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2252, in main
    getattr(buildout, command)(args)
  File "/home/x0045445/projects/testmockup/lib/python3.8/site-packages/zc/buildout/buildout.py", line 718, in install
    installed_develop_eggs = self._develop()
  File "/home/x0045445/projects/testmockup/lib/python3.8/site-packages/zc/buildout/buildout.py", line 961, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/home/x0045445/projects/testmockup/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1120, in develop
    call_subprocess(args)
  File "/home/x0045445/projects/testmockup/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 172, in call_subprocess
    raise Exception(
Exception: Failed to run command:
'/home/x0045445/projects/testmockup/bin/python3', '/tmp/tmpax5bjcc0', '-q', 'develop', '-mN', '-d', '/home/x0045445/projects/testmockup/develop-eggs/tmp7oqdxy25build'
```

I'd be happy to test it as well with some pointers on which buildout or setup I could use.
But if it's working for Maurits I'm also happy to just approve the PR 😃

**Comment by mauritsvanrees** [comment]
@spereverde In Plone 6, mockup is no longer a Python package, but pure javascript. The coredev buildout has it checked out. See https://github.com/plone/mockup#install on how to run it. 

Not mentioned there is that you need an older node version. I am running version 14 now, installed with nvm. Maybe 16 works too, 18 did not work for me yesterday.

**Comment by mauritsvanrees** [comment]
@spereverde Oh, you need to edit the Makefile in mockup and add one line. See my PR from yesterday:
https://github.com/plone/mockup/pull/1255/files

**Comment by spereverde** [comment]
@mauritsvanrees thanks for the tips! I will test this and get back to you asap

**Comment by petschki** [comment]
@spereverde there's also this google doc from the Classic-UI sprint where the mockup development is documented https://docs.google.com/document/d/1rX2tAeDC9eZzKycVDnJUf8guTQeA0G1aHSteQgVz_TU/edit#heading=h.fmct4qdv9fjr

**Comment by spereverde** [comment]
Also works for me inside buildout.coredev setup with the help of all info above.
Confirmed that you need node  v14.21.1. 
I also tried with 16, but that failed.

**Review by spereverde — APPROVED** [review]

**Pull request merged**
