### PR TITLE
Enhanced i18n to enable `pat-structure` review_state translation.

### PR DESCRIPTION
**Pull request by petschki**
successor of #1001

### CODE REVIEW

**Comment by erral** [comment]
It works like a charm!

French:
fr

Spanish:
es

Basque:
eu

**Review by erral — APPROVED** [review]
:clap:

**Comment by petschki** [comment]
Just found this one and fixed it too here https://github.com/plone/mockup/issues/1160

**Review by thet — APPROVED** [review]
:+1:

**Pull request merged**
