### PR TITLE
i18n fixes

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@erral shall I create a PR in `plone.app.locales` with the updated `widgets.pot` ?

**Comment by erral** [comment]
No, I will update it running the i18n scripts in buildout.coredev.

**Comment by petschki** [comment]
Can you guide me how to update the information in the README here https://github.com/plone/mockup?tab=readme-ov-file#i18n-message-extraction ?

**Comment by erral** [comment]
> Can you guide me how to update the information in the README here https://github.com/plone/mockup?tab=readme-ov-file#i18n-message-extraction ?

Sorry, I haven't realized this was in mockup repo.

The documentation is OK there, you can directly commit to plone.app.locales main branch after updating the pot file as stated there.

**Comment by petschki** [comment]
@erral done!

**Pull request merged**
