### PR TITLE
Fix building of the docs bundle 

### PR DESCRIPTION
**Pull request by thet**
Fix broken ``make docs`` task.
Now do:
``make bootstrap`` to install missing dependencies and a necessary symlink within node_modules
``make docs``
then do:
``python2 -m SimpleHTTPModule`` and open http://localhost:8000/mockup/ in the browser.

### CODE REVIEW

**Comment by vincentfretin** [comment]
Is this fixing https://github.com/plone/mockup/issues/980 ?

**Comment by thet** [comment]
@vincentfretin yes , that was exactly the error I got when building the docs.

**Comment by thet** [comment]
Just updated the PR to reference #980 in the commit message and news file

**Review by vincentfretin — APPROVED** [review]
great

**Comment by vincentfretin** [comment]
I really verified making the docs on Ubuntu 18.04. It works great.

**Comment by vincentfretin** [comment]
Question, how https://plone.github.io/mockup is updated?

**Comment by MrTango** [comment]
make publish-docs
i just did it, the docs are generated thru the gh-pages branch.

**Pull request merged**
