### PR TITLE
show quick edit/view for items in structure row

### PR DESCRIPTION
**Pull request by vangheem**
This is to address https://github.com/plone/Products.CMFPlone/issues/524

Here is a screenshot:
screen shot 2015-07-13 at 6 17 38 am

Thoughts?

### CODE REVIEW

**Comment by jensens** [comment]
At least the UI/UX team should have a look here (who to ping?)

**Comment by agitator** [comment]
@plone/ux-team what do you think about about @vangheem proposal?

I'd say the "eye" icon would be enough to solve that problem and to not add complexity

**Comment by davilima6** [comment]
My suggestion:

folder-contents-actions

**Comment by vangheem** [comment]
@davilima6 +1

**Comment by davilima6** [comment]
Btw any special reason for dropping the sorting arrows which stayed next to each column's title in Plone 4? I think that's way more intuitive usability-wise and would also help reducing the amount of buttons in that navbar (which now takes 3 (!) rows in screens smaller than 1200px).

**Comment by vangheem** [comment]
If I understand you correctly, rearrange is not meant to be a replacement for changing the display sort order. It permanently rearranges the items in the folder. It needs to be a button.

If you want to change the display sort on the items, that is done with the Query button.

**Comment by davilima6** [comment]
Thanks, only now I understand. Rearranging is a very powerful new feature, but also potentially dangerous imho since most sites base their navigation on folder position. My concern is similar to what currently happens with the Display menu: too often editors misconfigure their homepages and sections because that option is too visible and offers no contextual help so people just click away to test it. Maybe we should offer some warning that operation cannot be undone (just as when deleting an item)?

**Comment by vangheem** [comment]
Yes, this has been mentioned by others too. I think a warning confirmation prompt when you are on site root will suffice. Please create a ticket.

If you implement the arrows on the columns, please just make sure it is updating the query widget so those don't get out of sync.

**Comment by davilima6** [comment]
Opened: https://github.com/plone/mockup/issues/526

**Comment by djay** [comment]
I'm not sure the word workflow is used much elsewhere. it should be the same as the toolbar right?
I do agree rearrange is still likely to be mistaken for sorting the display. but other than a warning I'm not sure how to hide it. its really a power feature that is not going to be used much so it shouldn't be so prominent.

**Comment by djay** [comment]
BTW the quick edit buttons being closer to the left looks good to me. Maybe
a little small. Have to see if its fiddly to push.

**Comment by davilima6** [comment]
Did you really mean the workflow word? I imagined you meant Rearrange but that's not on the toolbar, is it?

I tried the Actions column on the left but it didn't look good as it related too much with the checkboxes. Since those are meant to be used on _batch_ actions, IMO having those markers on the left and individual item controls on the right resolved things clearer.

It will be less mistaken if the old arrows are there (instead of hidden inside a

**Comment by davilima6** [comment]
+1 on making Rearrange less prominent and suggest "hiding" it under "Actions on current folder", labeled "Rearrange items", just after "Select all contained items".

Btw I also suggest adopting `glyphicon-options-horizontal` there to match the one in `Actions` column (where users can also cut'n'copy an item). Because it's "more" not "configuration".

**Comment by vangheem** [comment]
no, rearrange won't work well on actions dropdown. A popover on a dropdown won't work. A warning message will suffice.

**Comment by agitator** [comment]
+1 for the proposal of @davilima6 
and please stick to the meaning of the issue title

**Comment by djay** [comment]
I think the actions are best just to the right of the title. If you are navigating around and doing actions on items then don't want to be going all the way over the to right. I don't mind @davilima6 suggestion if it was in the col to the right of title but @vangheem takes less space.

**Comment by vangheem** [comment]
We're all over the place here. I'm merging only to have one icon--link to the view of the item. It's less impactful and I think is a fine compromise here.

**Comment by agitator** [comment]
changed "workflow" to "state"

**Pull request merged**
