### PR TITLE
add a label to the select all checkbox and to each of the items in th…

### LINKED ISSUE #957: Structure pattern: select all and item selection checkboxes lack any label
@ionlizarazu

### PR DESCRIPTION
**Pull request by erral**
…e table to make the table more accessible

Fixes #957

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
Does this add text right of the select? Or is this just popover/ for screen-readers?

**Comment by erral** [comment]
It's a text just for screen readers, that's the reason to have the hiddenStructure class but an arial-label attribute.

**Pull request merged**
