### PR TITLE
Bootstrap 5.3

### PR DESCRIPTION
**Pull request by petschki**
Steps to do for a merge - please add/reduce if there is something missing

- [x] Mockup: Branch current master to `5.0.x`.
- [ ] Mockup: Merge `bs-53` to current master.
- [ ] Mockup: Create a `5.1.0-alpha.0` release (`make release-alpha` and choose `minor` version upgrade.)
- [ ] plone.staticresources: Branch current master to `2.0.x`.
- [ ] plone.staticresources `bs-53`: depend on mockup `5.1.0-alpha.0`.
- [ ] plone.staticresources `bs-53`: Build (`make all`).
- [ ] plone.staticresources `bs-53`: Eventually cleanup commits (git rebase with fixups and so.)
- [ ] plone.staticresources: Make a jenkins run.
- [ ] plone.staticresources: Merge `bs-53` into master.
- [ ] plone.staticresources: Make a release.
- [ ] plonetheme.barceloneta: Likewise as above:‌ Create new branch from current master, merge bs-53, release.
- [ ] plone.app.mosaic: Likewise as above.
- [ ] buildout.coredev `6.0`: Depend on new branches created above.
- [ ] buildout.coredev `6.1`: Create a 6.1 branch with master branches from above.

Eventually the plone.staticresources Jenkins run also needs plonetheme.barceloneta `bs-53`?

### CODE REVIEW

**Review by thet — COMMENTED** [review]
This LGTM!

@petschki @mauritsvanrees @santonelli 
I'd like to merge that ASAP, but Bootstrap 5.3 introduces some new CSS variables which are not present in Bootstrap 5.2 (`bs-secondary-bg`, `bs-emphasis-color`, `bs-gray-dark`.
It still might be low risk to merge that even if used in a Bootstrap 5.2 context with Plone 6.0.x because Bootstrap is also a direct dependency of Mockup. But that needs a little discussion and testing first.
Any opinions?

**Comment by santonelli** [comment]
First of all: I want to have Bootstrap 5.3 in as soon as possible.

As long as it's alpha we should not pull it in. I think "new features" should go into Plone 6.1. From a marketing-perspective 6.1 would be great to announce Bootstrap 5.3 for Classic UI including e.g. a Dark Mode for Barceloneta.

We could use the time to cleanup some variables and clarify the usage of variables in Plone vs. Sass vs. CSS. I'd drop Plone-specific variables entirely and stick to BS only. But this is a different discussion.

**Comment by rnixx** [comment]
Please take a look at https://github.com/plone/plonetheme.barceloneta/pull/320.

Bumping version here to 5.1.x and sticking the Plone 6 default to 5.0.x would do the trick.

**Comment by toalba** [comment]
Can we integrate the datatable-fix changes from master into here?

**Pull request merged**
