### PR TITLE
Update TinyMCE to version 4.7.13

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Comment by erral** [comment]
Yes, step by step :)

While waiting for the merge of 4.7.13 the 4.8.3 one was released.

Now I will update the static components of CMFPlone for both 5.1.x and master.

**Comment by sunew** [comment]
@thet @erral 
bower.json looks ok (except for the order and the plone version):

```
iff --git a/Products/CMFPlone/static/bower.json b/../mockup/bower.json
index 50bf181a6..bff753fac 100644
--- a/Products/CMFPlone/static/bower.json
+++ b/../mockup/bower.json
@@ -1,7 +1,6 @@
 {
-  "name": "Products.CMFPlone",
-  "version": "5.0b2",
-  "description": "CMFPlone Javascript Bundle",
+  "name": "mockup",
+  "description": "A collection of client side patterns for faster and easier web development",
   "dependencies": {
     "ace-builds": "1.2.6",
     "backbone": "1.1.2",
@@ -47,11 +46,8 @@
     "select2": "3.5.4",
     "selectivizr": "1.0.2",
     "tinymce-builded": "4.7.6",
-    "requirejs": "",
-    "less": "2.1.2",
-    "r.js": "2.1.15",
-    "cs-jqtree-contextmenu": "^0.1.0",
-    "js-shortcuts": "^1.0.1"
+    "js-shortcuts": "^1.0.1",
+    "cs-jqtree-contextmenu": "^0.1.0"
   },
   "devDependencies": {
     "expect": "0.3.1",
@@ -60,8 +56,8 @@
   "resolutions": {
     "bootstrap": "3.3.6",
     "jquery": "1.11.3",
+    "jquery-form": "3.51",
     "select2": "3.5.4",
-    "moment": "2.10.6",
-    "jquery-form": "3.51"
+    "moment": "2.10.6"
   }
 }

```

**Comment by erral** [comment]
AFAICT all version numbers are in sync between mockup's bower.json and CMFPlone's except TinyMCE, which was 4.5.6 instead of 4.7.6) and which I am updating now to this 4.7.13.

**Comment by thet** [comment]
Yes, I just saw that tinymce was at 4.5.6 ...

**Pull request merged**
