### PR TITLE
Mark special links: Do not mark anchors as special links. fixes gh-707

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Comment by frapell** [comment]
@jensens Please review, thanks :)

**Comment by jensens** [comment]
LGTM

**Comment by jensens** [comment]
To activate this change the bundles in Products.CMFPlone needs a rebuild.

**Comment by frapell** [comment]
@jensens How does this work? should I wait for a mockup release first?

Also, should I do it against master? as well as 5.1.x and 5.0.x branches?

**Comment by jensens** [comment]
@thet  - since you're the expert here I pass the question over to you :)

**Comment by frapell** [comment]
@thet How should I include this changes into CMFPlone? should I just compile master mockup? or do I need to wait for a release?

Plus, should I also compile it for 5.0.x and 5.1.x branches?

**Pull request merged**
