### PR TITLE
PR: Cleanup and rework: contenttype-icons and ...

### PR DESCRIPTION
**Pull request by fgrcon**
https://github.com/plone/Products.CMFPlone/issues/1226

### CODE REVIEW

**Comment by fgrcon** [comment]
https://travis-ci.org/plone/mockup/builds/90058035:
>PhantomJS 1.9.8 (Linux 0.0.0) TinyMCE "after each" hook FAILED
	TypeError: 'undefined' is not an object (evaluating 'doc.createRange') .....
    ✗ "after each" hook
TOTAL: 1 FAILED, 157 SUCCESS
1) "after each" hook
     TinyMCE .....

**already ocurred before my modifications**

**Comment by vangheem** [comment]
Why was this closed. You can ignore that error. It randomly fails all the time. We should remove the test.

Sorry, I haven't gotten around to reviewing. Is this still something you want to do?

**Comment by fgrcon** [comment]
i dont know what really happened. I never intended to close that (misclick?) . Please review and see:
https://github.com/fgrcon/Products.CMFPlone/blob/master/docs/icons_in_plone5.rst

**Comment by vangheem** [comment]
@fgrcon everything looks okay. Is there a jenkins job that ran all these tests together?

**Comment by fgrcon** [comment]
yes: http://jenkins.plone.org/job/pull-request-5.0/539  ( s.: https://github.com/plone/Products.CMFPlone/issues/1226)

**Pull request merged**
