### PR TITLE
Structure pattern: Filter UI improvements, etc.

### PR DESCRIPTION
**Pull request by thet**
Structure pattern:
- Show statusmessage with "Clear filter" button when filters are applied.
- Show visually if a filter is set.
- Allow multiple status messages.
- Display toolbar a bit compacter.

- Instead of clearing the filter when changing the path (initial approach from first commit) now there is a status message shown with a "Clear filter" button in it. For this to work it was necessary to allow multiple status messages. The "Clear filter" status message must always be present while other status messages must still be possible.
That way it should be very obvious that the current view is filtered.
- If a text filter is set, the filter input has a blue border.
- if a querystring is set, the magnifier icon has a blue background.
- The status messages look a bit nicer.

Applied filter:
Screenshot from 2020-02-03 02-01-54

New statusmessage design + more compact toolbar (no border-bottom, no margin-bottom, no min height):
Screenshot from 2020-02-03 02-00-09

Old statusmessage design:
Screenshot from 2020-02-03 01-50-18

Merge together:
https://github.com/plone/mockup/pull/937
https://github.com/collective/plone.app.locales/pull/286

### CODE REVIEW

**Comment by agitator** [comment]
Learning a new feature in Plone everday ... ;-)

My users use the text search feature to navigate quickly within folder structures with lots of content.

Never expected a feature like that, though I think it's neat, I also have my doubts that many users know and use it.

To make this feature useful imho a status message about activated filters is not helping much. I'd rather each query paramater as we do in a collection - but I think that should not be the scope of this improvement.

- I'd still say if a user filters the listing with a simple text entry, that entry should be reseted if one changes the location/context via breadcrumbs.
- If we really want to improve the querystring feature, we would have to add a collection like experience and add a query string element for searchable text (and remove) the text entry from that search field as soon as one adds further search query. This way it would be clearer what exactly happens

**Comment by thet** [comment]
I try so summarize the main question here:

Initially the idea was to clear the text filter as soon as the path changes. That is actually super simple and done in this commit: https://github.com/plone/mockup/pull/937/commits/cd19401381603d480e17007bbed9c2e7371339e2

After implementing this I found that I also have to clear the query filter. But just clearing all filters without a chance for the user to prevent seemed to harsh.
1) Query are not so easily built (many clicks necessary)
2) It could be quite useful to keep the query while browsing (e.g. filter for Images and Folders to browse for images).

To avoid another button like "Keep filter while browsing" I implemented it so that any filters/queries are kept while browsing but showing a "Clear Filter" button in a notification.

/cc @davilima6 @frapell @jensens @djay any input on this?

Referencing other Issues related to this PR here - for reference. I dont want to expand the scope of this PR any further:
https://github.com/plone/mockup/issues/381
https://github.com/plone/mockup/issues/671
https://github.com/plone/mockup/issues/672
https://github.com/plone/mockup/issues/678

**Comment by davilima6** [comment]
I like the described solution, will try to give it a go soon. Thanks, @thet!

**Comment by davilima6** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@davilima6 I don't understand - the notification in light-blue and the buttons when filter are applied in green? I'm absolutely open for color changes.
I noticed some flaws with the notifications. Currently the "drag/drop reorder" stacks upon multiple times. Have to rethink the notification system there.

**Comment by davilima6** [comment]
Agree, we should check if notification is already in list before appending it.

And to your question, yes. IMO:
* Only show the yellow one with exclamation mark to real warnings like `Cannot order item while querying`
* The one for "Some filters applied..." should be an info level only and have light blue background. I'd _try_ to avoid the red background also in the `Clear filters` button, maybe have a secondary background color, maybe white will give enough contrast with the blue background
* Success ones like "Successfully moved item" should be in green

**Comment by thet** [comment]
@davilima6 off topic: are you coming to the alpine city sprint? I plan to work on patternslib/mockup there: https://docs.google.com/document/d/172UtDjJbIfnoxHE_x67KkirOfnhcRJ1casBZlyjJGe0/edit#heading=h.7hs2swxej1x1

**Comment by davilima6** [comment]
@thet, unfortunately not this year :~ I'm taking vacations in homeland in the period 🇧🇷 But Salutations to All! Hope to be next year.

**Comment by thet** [comment]
@davilima6 enjoy the time!

**Pull request merged**
