### PR TITLE
Upgrade Jquery-related packages

### PR DESCRIPTION
**Pull request by davilima6**
Versions:
- jqtree: from version 1.4.1 to 1.4.10
- jquery-form: from 3.5.1 to 4.2.2
- NEW: bootstrap: from 3.3.6 to 3.4.1
- NEW: pickadate: from 3.5.6 to 3.6.4

### CODE REVIEW

**Comment by davilima6** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
Most recent jquery is 3.4.1! `jquery-migrate` should bring all BBB needed for older code. Would this be a path to go?

**Comment by fulv** [comment]
FYI, I upgraded Patternslib and ploneintranet.prototype to jquery 3.4.1, so
I might be able to help.  I did use jquery-migrate.
My only question is whether this is something that will be opposed by
people whose stuff will break with a newer jquery.
-- 
Fulvio

**Comment by davilima6** [comment]
Sounds good for Plone 6, so we have time to raise awareness in the community and migrate some addons before release.

**Comment by fulv** [comment]
I've started a ticket for jQuery 3:  #917

**Comment by davilima6** [comment]
I just found this [Plone Community thread ](https://community.plone.org/t/latest-usable-jquery-for-plone-4-3-1-11-3) which says a custom `$.buildFragment` must be implemented in order to use jQuery 1.12.4 with jQuery Tools.

OTOH I had no errors triggering modals with jQuery 1.12.4. I tried the ones in Dexterity Types control panel.

@fulv, did you experience this issue when upgrading jQuery? Did you do it for Plone 4, 5 or both?

**Comment by fulv** [comment]
@davilima6 I did not run into any issue related to `$.buildFragment`.  I upgraded for Plone 5.  My guess is it's not a dependency in Plone 5.

**Comment by davilima6** [comment]
Thanks! I'll update `p.staticresources` next

**Pull request merged**
