### PR TITLE
[a11y] focus handling in modal pattern

### LINKED ISSUE #11: accessible focus handling for overlays
- add anchor element around title of all overlays
- add anchor element around buttons/links which activate all overlays
- when overlay without a form is activated, set focus to the overlay title anchor 
- when overlay close link or overlay form cancel button are clicked, set focus to the originating button's anchor
- when close link loses focus, set focus to the overlay title anchor

### PR DESCRIPTION
**Pull request by nzambello**
Fixes #11.

Working on modal pattern:
- ARIA and roles attributes
- focus trap within modal
- focus handling in general about modal
- re-assign focus on modal opening link when closing
- close on click

### CODE REVIEW

**Comment by thet** [comment]
Hi, what's the status here?
Is the current outcome ready to merge?
No tests are here, but that would be acceptable.
Maybe give instead a short explanation how to reproduce the outcome of this PR.

**Comment by erral** [comment]
We have receivedn an a11y review of Plone 5, and modals are there too. 

We will check this PR if it fixes our requirements and report back.

**Comment by erral** [comment]
I rebased the PR and checked that it does what it promises and indeed now one gets the focus inside the modal, can close it and works as expected.

@ionlizarazu @nruiz

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by ionlizarazu** [comment]
A console error occurs when you click anywhere on the site. Furthermore, the popovers do not close if you click outside the element due to this error.
`Uncaught TypeError: Cannot read property 'hide' of undefined`
    `at r.hide (plone-compiled.js:5792)`
    `at HTMLDocument.<anonymous> (plone-compiled.js:5406)`
    `at HTMLDocument.dispatch (jquery.min.js:3)`
    `at HTMLDocument.$event.dispatch (jquery.event.drag.js:376)`
    `at HTMLDocument.r.handle (jquery.min.js:3)`
Peek 2020-04-28 10-44

**Comment by thet** [comment]
@ionlizarazu I can reproduce the problem with this branch. ``self.loading`` is undefined in https://github.com/plone/mockup/blob/db7843e7f1cb418198e098d66e5bddcd42bca036/mockup/patterns/modal/pattern.js#L898

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
Can you check this @thet @nzambello ?

**Comment by thet** [comment]
@erral @nzambello @ionlizarazu merged!
sorry it took so long...

**Comment by mauritsvanrees** [comment]
Mockup branch 3.x contains this change. When I compile the resources into `plone.staticresources`, I get a test failure. See https://github.com/plone/plone.staticresources/pull/104#issuecomment-715598174.

```
$ bin/test --all -s Products.CMFPlone -m test_robot -t "A page is opened to edit in TinyMCE"
...
==============================================================================
Test Tinymce                                                                  
==============================================================================
Scenario: A page is opened to edit in TinyMCE                         | FAIL |
Element 'css=.pattern-relateditems-result-select.selectable' not visible after 30 seconds.
------------------------------------------------------------------------------
Test Tinymce                                                          | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /Users/maurits/community/plone-coredev/5.2/parts/test/test_tinymce/Scenario_A_page_is_opened_to_edit_in_TinyMCE/output.xml

Failure in test Scenario A page is opened to edit in TinyMCE (test_tinymce.robot)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/2.7.17/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/maurits/shared-eggs/cp27m/robotsuite-2.2.1-py2.7.egg/robotsuite/__init__.py", line 475, in runTest
    assert last_status == 'PASS', last_message
AssertionError: Element 'css=.pattern-relateditems-result-select.selectable' not visible after 30 seconds.
```

When I revert the change from this PR, and recompile the resources, the error is gone.
Could someone look into this?

Note: maybe the test simply needs an update.

Also note that theoretically you could completely break `mockup` with a change and not get a failure on Jenkins. The failures only surface when `./bin/plone-compile-resources` is run to let the changes end up in `plone.staticresources`. It would be nice if failures would already get caught when a change in `mockup` is made. But this may be tricky.

**Comment by mauritsvanrees** [comment]
I have reverted the last commit, and am wondering if I should revert the first as well, although I don't see a problem with it.
I created an issue for this: https://github.com/plone/mockup/issues/1029

I only reverted it on the new branch 3.x for now, not yet on master.

**Comment by mauritsvanrees** [comment]
Sorry, but I have reverted the rest of this PR as well, see https://github.com/plone/mockup/issues/1029#issuecomment-718008632

Let me be clear: the changes in this PR certainly seem good and are welcome, but they have side effects that were not detected earlier. I hope this can get resolved.

**Comment by petschki** [comment]
some more notes on this: we're experiencing problems with mosaic modals, eg. you cannot remove a criteria in the `existingcontenttile` modal anymore and the path navigation in `relateditemspattern` in modals is completely broken like @mauritsvanrees mentioned above. With deactivated `self.activateFocusTrap();``everything works like it should agaign.

**Comment by petschki** [comment]
just mentioning, that I've reverted this PR also in `barceloneta-lts` branch right now https://github.com/plone/mockup/commit/008b03617d611956a49b7980d58594fdf28baed9

**Pull request merged**
