### PR TITLE
Implement support for rooted Navigation in relatedItems pattern by allowing an optional rootPath parameter.

### PR DESCRIPTION
**Pull request by alecpm**

### CODE REVIEW

**Comment by thet** [comment]
@alecpm why are you using the 1.x branch here? For my Plone 4.x / plone.app.widgets 1.x based project, I'm using mockup master...

**Comment by alecpm** [comment]
@thet isn't the intent of 1.x branch that it be used with Plone 4.x and without plone.app.contenttypes (i.e. with plone.app.widgets 1.x branch)?

**Comment by thet** [comment]
@alecpm the Mockup 2.x branch was created because the Patternslib and Mockup merged and the pattern definition API has changed. But since all Mockup patterns were updated, that should not be a problem to use Mockup 2.x with plone.app.widgets 1.x.
I have already updated the widgets bundle in plone.app.widgets based on Mockup 2.x, but that wasn't released until now.
I'd just target latest Mockup unless you have a lot of custom patterns, which are not updated to support the new pattern definition API.

**Comment by alecpm** [comment]
Hm, I merged in changes from mockup 1.x to p.a.widgets 1.x here https://github.com/plone/plone.app.widgets/pull/128. Perhaps that was a mistake.

**Comment by thet** [comment]
No prob. Are these changes already in mockup 2.x? Then we can just build a widgets bundle from latest mockup and update it in plone.app.widgets.

**Comment by thet** [comment]
Btw, I'm looking forward for this feature/fix!

**Comment by alecpm** [comment]
They are in 1.x and master, should be trivial to merge into 2.x though.

**Comment by alecpm** [comment]
I still need to backport some of the fixes from p.a.dexterity, p.a.z3cforms, master etc. into p.a.widgets though.

**Comment by alecpm** [comment]
@thet OK, I'm a bit confused I don't see a 2.x branch of mockup in github. Am I missing something?

**Comment by thet** [comment]
@alecpm yes, it's just the master branch

**Pull request merged**
